services:
  goc-controller:
    image: ghcr.io/laugmanuel/goc:main
    container_name: goc-controller
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      # docker socket is needed to manage containers
      - /var/run/docker.sock:/var/run/docker.sock

      # GOC_WORKSPACE is the workspace directory for all stacks. Keep it in sync between host and container
      - ${GOC_WORKSPACE}:${GOC_WORKSPACE}
